# Explicitly set output directory for auxiliary files
$out_dir = "logs";             # Auxiliary files go here
$pdf_mode = 1;                 # Generate PDF

# Complex pdflatex command to force separation
$pdflatex = 'pdflatex -output-directory=logs -aux-directory=logs %O %S && cp logs/*.pdf .';

# Cleanup commands
$clean_ext = "aux bbl bcf blg fdb_latexmk fls log nav out run.xml snm synctex.gz toc";

sub cleanup_dirs {
    my $dir;
    foreach $dir ($out_dir, $pdf_dir) {
        if (-d $dir) {
            unlink glob "$dir/*.$_" for split ' ', $clean_ext;
        }
    }
}
push @clean_up_subdirs, \&cleanup_dirs;
