# Taps
tap "sodium-hydroxide/compression-tools", "https://github.com/sodium-hydroxide/compression-tools"
brew "compression-tools"
tap "sodium-hydroxide/lsdir", "https://github.com/sodium-hydroxide/lsdir"
# brew "lsdir"

# Formulae
brew "nvim"
brew "bash"         # version in macOS is outdated
brew "wget"         # similar to curl
brew "git"
brew "ripgrep"      # regex tool
brew "fd"           # find directories
brew "gh"
brew "tmux"
brew "lf"               # needs confix
brew "massren"
brew "ffmpeg"
brew "htop"
brew "duti"
brew "mas"
brew "doxygen"
brew "help2man"
brew "gcc"
brew "texlive"
brew "julia"

# Casks
cask "bbedit"
cask "backblaze"
cask "docker"
cask "calibre"
cask "zotero"
cask "hiddenbar"
cask "orion"
cask "plex"
cask "grandperspective"
cask "pdf-expert" # needs license
cask "whatsapp"
cask "backblaze"
cask "mission-control-plus"
cask "xquartz"
cask "visual-studio-code"
cask "wine-stable"
cask "vlc"
cask "skim"
cask "netnewswire"
cask "aldente"
cask "obsidian"
cask "font-jetbrains-mono-nerd-font"
cask "iterm2"


