# Taps
tap "sodium-hydroxide/compression-tools", "https://github.com/sodium-hydroxide/compression-tools"
brew "compression-tools"
# tap "sodium-hydroxide/lsdir", "https://github.com/sodium-hydroxide/lsdir"
# brew "libmagic"
# brew "lsdir"

# Editors
brew "neovim"
brew "luarocks"
brew "utf8proc"
cask "vimr"
cask "bbedit"
cask "visual-studio-code"
cask "zed"
cask "obsidian"
brew "glow"         # Markdown previewer


# Dev Tools
brew "git"
brew "gh"
cask "docker"
cask "iterm2"

# Languages
brew "bash"         # version in macOS is outdated
brew "perl"
brew "ruby"
brew "julia"
brew "gcc"
brew "llvm"
brew "sbcl"
brew "texlive"      # latex
brew "pandoc"       # converting to and from latex

# Utilities
brew "mas"          # Mac App Store
brew "wget"         # similar to curl
brew "ripgrep"      # regex tool
brew "fd"           # find directories
brew "tmux"
brew "lf"               # needs confix
brew "massren"      # rename files
brew "ffmpeg"       # audio and video editing
brew "htop"         # see processes running
brew "duti"         # set default applications macOS
brew "doxygen"      # create documentation from comments
brew "help2man"     # create man page from -h or --help flag
brew "cmake"
brew "ninja"
cask "hiddenbar"
cask "grandperspective"
cask "mission-control-plus"
cask "xquartz"
cask "wine-stable"
cask "aldente"


# General
cask "calibre"
cask "zotero"
cask "orion"
cask "plex"
cask "pdf-expert" # needs license
cask "whatsapp"
cask "backblaze"
cask "vlc"
cask "skim"
cask "netnewswire"

# Fonts

cask "font-jetbrains-mono-nerd-font"

