[manager]
ratio = [1, 3, 4]
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
sort_translit = true
linemode = "permissions_and_size"
show_hidden = false  # want to get a toggle for this
show_symlink = true  # show path to original
mouse_events = [
    "click",
    "scroll",
    "touch",
    "move",
    "drag"
]
title_format = "{cwd}"

[preview]
wrap = "no"
tab_size = 4
# max_width
# max_height
# image_delay
# image_filter
# image_quality
# sizel_fraction
# ueberzug_scale
# ueberzug_offset

# [opener]
# [open]
# [tasks]
# [plugin]
# [input]
# [confirm]
# [pick]
# [which]

